modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0"
[[mods]]
modId="acedium"
version="${version}"
displayName="Acedium"
#logoFile="assets/nvidium/nvidium.png"
authors="Cortex, Ferri_Arnus"
description='''
Experimental port of nvidium, bugs will be present
Replacement rendering engine for sodium/embeddium
'''

[[dependencies.acedium]]
modId = "neoforge"
mandatory = true
versionRange = "[20.3.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.acedium]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.3,1.20.5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.acedium]]
modId = "embeddium"
mandatory = true
versionRange = "[0.2.2+mc1.20.1, )"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "nvidium.mixins.json"

[[mods]]
modId="nvidium"
displayName="Nvidium (Acedium)"
version="${version}"
authors="Cortex"
logoFile="assets/nvidium/nvidium.png"
description='''
Experimental port of nvidium, bugs will be present
Replacement rendering engine for sodium/embeddium
'''